[package]
name = "lato-extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
dunce = "1"
lato-core = { path = "../lato-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "sync"] }

[dev-dependencies]
tempfile = "3"
