[package]
name = "lato-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
lato-core = { path = "../lato-core" }
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }

[dev-dependencies]
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
